# Generated by Django 3.2.7 on 2021-11-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_drug_oncallpharmacy_pharmacydrug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oncallpharmacy',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='oncallpharmacy',
            name='start_hour',
        ),
        migrations.AlterField(
            model_name='oncallpharmacy',
            name='end_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='oncallpharmacy',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
