# Generated by Django 3.2.7 on 2021-09-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_pharmacy_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='image',
            field=models.FilePathField(path='/home/josh/projects/proxyPharmBackend/media//images/pharmacies/'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='thumbnail_image',
            field=models.FilePathField(default='', path='/home/josh/projects/proxyPharmBackend/media//images/pharmacies/thumbnails/'),
        ),
    ]
