# Generated by Django 3.2.7 on 2021-09-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210926_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FilePathField(blank=True, default=None, null=True, path='/home/josh/projects/proxyPharmBackend/media//images/users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
